# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src/reflect
src/generic
src/mulle-atexit
src/mulle-atinit
src/mulle-stacktrace
src
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-core-all-load-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/include-private.h
src/mulle-atexit/include-private.h
src/mulle-atinit/include-private.h
src/mulle-stacktrace/include-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
src/mulle-atexit/_mulle-atexit-include-private.h
src/mulle-atinit/_mulle-atinit-include-private.h
src/mulle-stacktrace/_mulle-stacktrace-include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-core-all-load-include.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/include.h
src/mulle-atexit/include.h
src/mulle-atinit/include.h
src/mulle-stacktrace/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/mulle-atexit/mulle-atexit.h
src/mulle-atexit/_mulle-atexit-include.h
src/mulle-atinit/mulle-atinit.h
src/mulle-atinit/_mulle-atinit-include.h
src/mulle-core-all-load.h
src/mulle-stacktrace/mulle-stacktrace.h
src/mulle-stacktrace/_mulle-stacktrace-include.h
src/mulle-stacktrace/_mulle-stacktrace-versioncheck.h
)

