# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
mulle-core-all-load/mulle-atexit/mulle-atexit.c
mulle-core-all-load/mulle-atinit/mulle-atinit.c
mulle-core-all-load/mulle-core-all-load.c
mulle-core-all-load/mulle-stacktrace/mulle-stacktrace-backtrace.c
mulle-core-all-load/mulle-stacktrace/mulle-stacktrace.c
mulle-core-all-load/mulle-stacktrace/mulle-stacktrace-execinfo.c
mulle-core-all-load/mulle-stacktrace/mulle-stacktrace-nop.c
)
